services:
  next_dev:
    container_name: next15_typescript_eslint_tailwind_starter_dev
    build: .
    env_file:
      - .env
    environment:
      # Для Hot Reload
      - WATCHPACK_POLLING=true
    ports:
      - "${EXTERNAL_PORT}:3000"
      - "24678:24678" # hmr
    volumes:
      - "./app:/app/"
      - "./logs:/root/.npm/_logs"
    restart: always
    command: bash -c "npm run dev"
    # Debug Mode:
    # command: bash -c "node -e 'function debug () { setTimeout(debug, 100000000) }; debug()'"
