import "@/styles/globals.css";
import type { TMetadata } from "@/models/Types/TMetadata";
import { TWithChildren } from "@/models/Types/TChildren";

export const metadata: TMetadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<TWithChildren>) {
  return (
    <html lang="ru">
      <body className={`font-Sans antialiased`}>
        <div className="bg-gray-700">
          <h1>MAIN LAYOUT</h1>
          {children}
        </div>
      </body>
    </html>
  );
}
